/*
 * generated by Xtext
 */
package org.rlogiacco.eclipse.jbehave;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JBehaveDSLRuntimeModule extends org.rlogiacco.eclipse.jbehave.AbstractJBehaveDSLRuntimeModule {

}
