/*
* generated by Xtext
*/
package org.rlogiacco.eclipse.jbehave.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.rlogiacco.eclipse.jbehave.jBehaveDSL.Narrative;
import org.rlogiacco.eclipse.jbehave.jBehaveDSL.Step;
import org.rlogiacco.eclipse.jbehave.jBehaveDSL.Story;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class JBehaveDSLLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public JBehaveDSLLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	String text(Story ele) {
		return ele.getTitle();
	}
	
	String text(Narrative ele) {
		return ele.getTitle();
	}
	
	String text(Step ele) {
		return ele.getType() + " " + ele.getDescription();
	}

/*
	String image(Story ele) {
      return "story.gif";
    }
    
    String image(Narrative ele) {
      return "narrative.gif";
    }
	 
    String image(Step ele) {
      return "step.gif";
    }
*/
}
