/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.jbehave.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class JbehaveWebModule extends AbstractJbehaveWebModule {
}
