/*
* generated by Xtext
*/
package org.rlogiacco.eclipse.jbehave.ui.contentassist;

import org.rlogiacco.eclipse.jbehave.ui.contentassist.AbstractJBehaveDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JBehaveDSLProposalProvider extends AbstractJBehaveDSLProposalProvider {

}
