/*
* generated by Xtext
*/
package org.agileware.natural.jbehave.ui.contentassist;

import org.agileware.natural.jbehave.ui.contentassist.AbstractJbehaveProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JbehaveProposalProvider extends AbstractJbehaveProposalProvider {

}
