/*
 * generated by Xtext
 */
package org.rlogiacco.eclipse.cucumber;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CucumberDSLRuntimeModule extends org.rlogiacco.eclipse.cucumber.AbstractCucumberDSLRuntimeModule {

}
