/*
 * generated by Xtext
 */
package org.agileware.natural.jbehave.tests

import com.google.inject.Inject
import org.agileware.natural.jbehave.jbehave.Story
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith

import static org.hamcrest.CoreMatchers.*
import static org.hamcrest.MatcherAssert.*

@RunWith(XtextRunner)
@InjectWith(JBehaveInjectorProvider)
class JBehaveParsingTest {
	
	@Inject
	ParseHelper<Story> parseHelper
	
	@Test
	def void parseHappyPath() {
		val result = parseHelper.parse('''
			Narrative:
			In order to sell a pet
			As a store owner
			I want to add a new pet to the catalog
			
			Scenario: Adding a pet
			Meta:
			@tag component:Pet Store Api
			
			Given I have the following pet:
			|name | status    |
			|Fido | available |
			When I add the pet to the store
			Then the pet should be available in the store
		''')
		
		assertThat(result, notNullValue())
		assertThat(result.eResource.errors, equalTo(#[]))
	}
}
