/*
 * generated by Xtext
 */
package org.rlogiacco.eclipse.cucumber.ui.labeling;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Background;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Examples;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Feature;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Scenario;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.ScenarioOutline;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Step;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Table;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Tag;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class CucumberDSLLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public CucumberDSLLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	String text(Feature ele) {
		return merge(ele.getDescription());
	}

	String image(Feature ele) {
		return "feature.png";
	}

	String text(Background ele) {
		return merge(ele.getDescription());
	}

	String image(Background ele) {
		return "background.gif";
	}

	String text(Scenario ele) {
		return merge(ele.getDescription());
	}

	String image(Scenario ele) {
		return "scenario.gif";
	}

	String text(ScenarioOutline ele) {
		return merge(ele.getDescription());
	}

	String image(ScenarioOutline ele) {
		return "scenario.gif";
	}

	String text(Step ele) {
		return ele.getDescription();
	}

	String image(Step ele) {
		return "step.gif";
	}

	String text(Table ele) {
		return "Table of " + ele.getRows().size() + " rows";
	}

	String image(Table ele) {
		return "table.gif";
	}

	String text(Examples ele) {
		return merge(ele.getDescription()).isEmpty() ? "Example" : merge(ele.getDescription());
	}

	String image(Examples ele) {
		return "example.gif";
	}

	String text(Tag ele) {
		return ele.getName();
	}

	String image(Tag ele) {
		return "annotation.gif";
	}
	
	private static String merge(EList<String> strings) {
		StringBuilder builder = new StringBuilder();
		for (String string : strings) {
			builder.append(string);
		}
		return builder.toString();
	}
}
