/*
* generated by Xtext
*/
package org.rlogiacco.eclipse.cucumber.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Feature;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Scenario;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Step;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class CucumberDSLLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public CucumberDSLLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	String text(Feature ele) {
		return ele.getTitle();
	}
	
	String text(Scenario ele) {
		return ele.getTitle();
	}
	
	String text(Step ele) {
		return ele.getType() + " " + ele.getDescription();
	}

/*
	String image(Feature ele) {
      return "feature.gif";
    }
    
    String image(Scenario ele) {
      return "scenario.gif";
    }
	 
    String image(Step ele) {
      return "step.gif";
    }
*/
}
