/*
 * generated by Xtext
 */
package org.rlogiacco.eclipse.cucumber.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Line;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Model;

/**
 * customization of the default outline structure
 * 
 */
public class CucumberDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	protected void _createChildren(DocumentRootNode parentNode, Model domainModel) {
		createNode(parentNode, domainModel.getFeature());
	}
	
	protected void _createNode(IOutlineNode parentNode, Line modelElement) {
		// do not show as node in the outline
	}
}
