/*
* generated by Xtext
*/
package org.rlogiacco.eclipse.cucumber.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CucumberDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
