/*
 * generated by Xtext
 */
package org.rlogiacco.eclipse.cucumber.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Step;
import org.rlogiacco.eclipse.cucumber.cucumberDSL.Table;

/**
 * customization of the default outline structure
 * 
 */
public class CucumberDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
	protected boolean _isLeaf(Table modelElement) {
		// do not allow expansion of table nodes
		return true;
	}
	
	protected boolean _isLeaf(Step modelElement) {
		// only allow expansion of step nodes with tables
		return modelElement.getTable() == null;
	}
}
