/*
 * generated by Xtext
 */
package org.rlogiacco.eclipse.cucumber.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CucumberDSLUiModule extends org.rlogiacco.eclipse.cucumber.ui.AbstractCucumberDSLUiModule {
	public CucumberDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
		return CucumberDSLHyperlinkHelper.class;
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	    return CucumberDSLHighlightingConfiguration.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		 return CucumberDSLSemanticHighlightingCalculator.class;
	}
	
//	@Override
//	public Class<? extends org.eclipse.xtext.builder.IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
//		return org.eclipse.xtext.builder.BuilderParticipant.class;
//	}
}
