/*
 * generated by Xtext
 */
package org.rlogiacco.eclipse.jbehave.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JBehaveDSLUiModule extends org.rlogiacco.eclipse.jbehave.ui.AbstractJBehaveDSLUiModule {
	public JBehaveDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
