/*
 * generated by Xtext
 */
package org.agileware.natural.jbehave.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JBehaveUiModule extends org.agileware.natural.jbehave.ui.AbstractJBehaveUiModule {
	public JBehaveUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
