/*
 * generated by Xtext
 */
package org.agileware.natural.jbehave.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JbehaveUiModule extends org.agileware.natural.jbehave.ui.AbstractJbehaveUiModule {
	public JbehaveUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
