/*
 * generated by Xtext
 */
package org.agileware.natural.jbehave;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JBehaveRuntimeModule extends org.agileware.natural.jbehave.AbstractJBehaveRuntimeModule {

}
