/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.jbehave;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JbehaveRuntimeModule extends org.agileware.natural.jbehave.AbstractJbehaveRuntimeModule {

}
