/*
* generated by Xtext
*/
package org.rlogiacco.eclipse.jbehave.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JBehaveDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
