/*
 * generated by Xtext 2.23.0-SNAPSHOT
 */
package org.agileware.natural.lang.ide;


/**
 * Use this class to register ide components.
 */
public class NaturalIdeModule extends AbstractNaturalIdeModule {
}
