/*
 * generated by Xtext 2.23.0-SNAPSHOT
 */
package org.agileware.natural.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.agileware.natural.lang.NaturalRuntimeModule;
import org.agileware.natural.lang.NaturalStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class NaturalIdeSetup extends NaturalStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new NaturalRuntimeModule(), new NaturalIdeModule()));
	}
	
}
