/*
* generated by Xtext
*/
package org.agileware.natural.jbehave.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JBehaveOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
