/*
 * generated by Xtext
 */
package org.agileware.natural.jbehave.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.agileware.natural.jbehave.JBehaveRuntimeModule;
import org.agileware.natural.jbehave.JBehaveStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JBehaveIdeSetup extends JBehaveStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JBehaveRuntimeModule(), new JBehaveIdeModule()));
	}
	
}
