/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.jbehave.ide;


/**
 * Use this class to register ide components.
 */
public class JbehaveIdeModule extends AbstractJbehaveIdeModule {
}
