/*
* generated by Xtext
*/
package org.rlogiacco.eclipse.cucumber.ui.contentassist;

import org.rlogiacco.eclipse.cucumber.ui.contentassist.AbstractCucumberDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CucumberDSLProposalProvider extends AbstractCucumberDSLProposalProvider {

}
