/*
 * generated by Xtext
 */
package org.agileware.natural.cucumber;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CucumberRuntimeModule extends org.agileware.natural.cucumber.AbstractCucumberRuntimeModule {

}
