/*
 * generated by Xtext
 */
package org.agileware.natural.cucumber;

import org.agileware.natural.stepmatcher.DefaultStepMatcher;
import org.agileware.natural.stepmatcher.IStepMatcher;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class CucumberRuntimeModule extends org.agileware.natural.cucumber.AbstractCucumberRuntimeModule {

	public Class<? extends IStepMatcher> bindIStepMatcher() {
		return DefaultStepMatcher.class;
	}
}
