/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.cucumber.ide;


/**
 * Use this class to register ide components.
 */
public class CucumberIdeModule extends AbstractCucumberIdeModule {
}
