/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.cucumber.jvm5;

import org.junit.runner.RunWith;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;

@RunWith(Cucumber.class)
@CucumberOptions(plugin = { "pretty" })
public class LibraryTest {

}
