/*
 * generated by Xtext 2.23.0-SNAPSHOT
 */
package org.agileware.natural.lang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NaturalStandaloneSetup extends NaturalStandaloneSetupGenerated {

	public static void doSetup() {
		new NaturalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
