/*
 * generated by Xtext 2.23.0-SNAPSHOT
 */
package org.agileware.natural.lang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NaturalRuntimeModule extends AbstractNaturalRuntimeModule {
}
