/*
 * generated by Xtext
 */
package org.agileware.natural.cucumber.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

import static org.agileware.natural.cucumber.tests.CucumberTestHelpers.EXAMPLE_FEATURE

@RunWith(XtextRunner)
@InjectWith(CucumberInjectorProvider)
class CucumberFormatterTest {

	@Inject CucumberTestHelpers _th

	@Test
	def void simpleFormatting() {
		val toBeFormatted = '''
			@alpha  @beta  
			Feature: The quick brown fox  
				Jumps over  
				The lazy dog
			Scenario: Jack and Jill  
				When Jack falls down  
				Then Jill comes tumbling after  
		'''
		val expectation = '''
			@alpha
			@beta
			Feature: The quick brown fox
				Jumps over  
				The lazy dog
			
			Scenario: Jack and Jill
				When Jack falls down
				Then Jill comes tumbling after
		'''
		_th.assertFormatted(toBeFormatted, expectation)
	}

	@Test
	def void indentSteps() {
		val toBeFormatted = '''
			Feature: Jack and Jill
			
			Scenario: Jack falls down
			When Jack falls down
			Then Jill comes tumbling after
		'''
		val expectation = '''
			Feature: Jack and Jill
			
			Scenario: Jack falls down
				When Jack falls down
				Then Jill comes tumbling after
		'''
		_th.assertFormatted(toBeFormatted, expectation)
	}
	
	@Test
	def void preserveValidFormatting() {
		_th.assertFormatted(EXAMPLE_FEATURE)
	}
}
